version: '3'

networks:
  laravel:


services:
  app:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
    networks:
      - laravel

  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel
  postgres:
      image: postgres:13.3
      container_name: postgres
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: laraveldb
      ports:
        - "5432:5432"
      volumes:
        - postgres:/var/lib/postgresql/data
      networks:
        - laravel
  pgadmin:
    image: dpage/pgadmin4:5.2 #@TODO - must know why isn't possible to load servers.json on newest image version
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - "pgadmin:/var/lib/pgadmin"
      - "./docker/servers.json:/pgadmin4/servers.json"
    networks:
      - laravel

volumes:
  postgres:
  pgadmin: